<!DOCTYPE html>
<html lang="en">
<head>
    <base href="<?= BASE_URL ?>">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Estilo Sidewalk</title>
</head>
<body>
    <h1>ESTILO SIDEWALK</h1>
    <nav>
        <a href="">Home</a>
        <a href="">Calzados</a>
        <a href="">Marcas</a>
        <a href="">ADD Calzado</a>
        <a href="">ADD Marca</a>

        <a href="login">Log in</a>
        <a href="logout">Log out</a>
    </nav> 
    </h1>
</body>
</html>