<?php require 'templates/header.phtml' ?>

<div class="mt-5 w-25 mx-auto">
    <form action='formCalzados<?php if (isset($id_calzado)) {echo "/" . $id_calzado; } ?>' method="post">
        <input type="text" name="nombre" placeholder="Ingrese Nombre">
        <input type="number" name="precio" placeholder="Ingrese Precio">
        <label for="">Seleccione la marca</label>
        <select name="marca" id="" >

            <?php
            if (!isset($data)) { ?>
                <option value="">No hay marcas</option>
                <?php
            } else {
                foreach ($data as $marca) { ?>
                    <option value="<?= $marca->id_marca ?>"><?= $marca->nombre ?></option>
            <?php
                }
            }
            ?>
        </select>
        <input type="text" name="tipo" placeholder="Ingrese tipo de calzado">
        <input type="number" name="talle"placeholder="Ingrese el talle">
        <input type="text" name="descripción" placeholder="Ingrese la descripción">
        <?php if (isset($id_calzado)) { ?>
            <button type="submit" class="btn btn-primary mt-3">Modificar Calzado</button>
        <?php
        } else { ?>
            <button type="submit" class="btn btn-primary mt-3">Agregar Calzado</button>
        <?php } ?>
    </form>
</div>

<?php require 'templates/footer.phtml' ?>