<?php require '../templates/header.phtml' ?>

<ul class="list-group list-group-item-info">
    <li class="list-group-item list-group-item-action list-group-item-info">
        <div>
            <b><?= $data->id_marca ?></b> | <?=substr($data->nombre,0,25)?>
            <button><a href="formMarcas/<?=$data->id_marca ?>">Editar</a></button>
            <button><a href="marcas">Volver</a></button>
            <button><a href="deleteMarca/<?=$data->id_marca ?>">Borrar</a></button>
        </div>
    </li>
</ul>

<?php require '../templates/footer.phtml' ?>